FROM python:3.10

# install google chrome
RUN apt-get -y update
RUN apt-get install -y chromium
COPY . /app
WORKDIR /app
# upgrade pip
RUN pip install --upgrade pip
# install selenium
RUN pip install -r requirements.txt
ENTRYPOINT ["python","main.py"]